- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Setting variables
  set_fact:
    docker_script: "~/Download/get-docker.sh"
- name: Download docker script
  get_url:
    url:  https://get.docker.com
    dest: "{{ docker_script }}"
- name: Run docker installation script
  shell: "sh {{ docker_script }}"


#- name: Install apache httpd  (state=present is optional)
#  apt:
#    name: docker
#    state: present
