- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Download docker script
  shell: "curl -fsSL https://get.docker.com -o get-docker.sh"


#- name: Install apache httpd  (state=present is optional)
#  apt:
#    name: docker
#    state: present
