- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Setting variables
  set_fact:
    docker_gpg_key: "~/Downloads/docker_gpg.txt"
- name: Install required system packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: no
  loop: [ 'vim', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'gnupg-agent']
- name: Download GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: "{{ docker_gpg_key }}"

#- name: Install apache httpd  (state=present is optional)
#  apt:
#    name: docker
#    state: present
